"use client"

/** Auto-generated by scripts/gen-next-page-registry.mjs — do not edit by hand. */
import type { ComponentType } from "react"
import { withNavigate } from "@/lib/withNavigate"
import HomePage from "@/views/HomePage"
import LegalPage from "@/views/LegalPage"

import AboutPageRaw from "@/views/practice/AboutPage"
import AdoptionVisa102PageRaw from "@/views/partner-family/AdoptionVisa102Page"
import AgedDependentRelativePageRaw from "@/views/partner-family/AgedDependentRelativePage"
import AgedParent804PageRaw from "@/views/partner-family/AgedParent804Page"
import ARTReviewPageRaw from "@/views/reviews/ARTReviewPage"
import AssuranceOfSupportPageRaw from "@/views/partner-family/AssuranceOfSupportPage"
import AustralianCitizenshipPageRaw from "@/views/visitor-other/AustralianCitizenshipPage"
import BalanceOfFamilyTestPageRaw from "@/views/partner-family/BalanceOfFamilyTestPage"
import BlogPageRaw from "@/views/practice/BlogPage"
import BookConsultationPageRaw from "@/views/BookConsultationPage"
import BookPageRaw from "@/views/BookPage"
import BridgingVisasPageRaw from "@/views/visitor-other/BridgingVisasPage"
import CarerVisaPageRaw from "@/views/partner-family/CarerVisaPage"
import ChangeOfEmployerPageRaw from "@/views/employer-sponsored/ChangeOfEmployerPage"
import ChecklistsPageRaw from "@/views/practice/ChecklistsPage"
import ChildVisa101PageRaw from "@/views/partner-family/ChildVisa101Page"
import ChildVisa802PageRaw from "@/views/partner-family/ChildVisa802Page"
import ContactPageRaw from "@/views/ContactPage"
import ContributoryAgedParent864PageRaw from "@/views/partner-family/ContributoryAgedParent864Page"
import ContributoryAgedParent884PageRaw from "@/views/partner-family/ContributoryAgedParent884Page"
import ContributoryParent143PageRaw from "@/views/partner-family/ContributoryParent143Page"
import ContributoryParent173PageRaw from "@/views/partner-family/ContributoryParent173Page"
import CoreSkillsOccupationListPageRaw from "@/views/employer-sponsored/CoreSkillsOccupationListPage"
import CoreSkillsStreamPageRaw from "@/views/employer-sponsored/CoreSkillsStreamPage"
import CoursesPRProspectsPageRaw from "@/views/student/CoursesPRProspectsPage"
import DAMAPageRaw from "@/views/employer-sponsored/DAMAPage"
import DependentChild445PageRaw from "@/views/partner-family/DependentChild445Page"
import EmployerNomination186PageRaw from "@/views/employer-sponsored/EmployerNomination186Page"
import EmployerObligationsPageRaw from "@/views/employer-sponsored/EmployerObligationsPage"
import EmployerSponsorshipPageRaw from "@/views/employer-sponsored/EmployerSponsorshipPage"
import EnglishRequirementsPageRaw from "@/views/skilled/EnglishRequirementsPage"
import Eta601PageRaw from "@/views/visitor-other/Eta601Page"
import Evisitor651PageRaw from "@/views/visitor-other/Evisitor651Page"
import GenuinePositionPageRaw from "@/views/employer-sponsored/GenuinePositionPage"
import GenuineStudentRequirementPageRaw from "@/views/student/GenuineStudentRequirementPage"
import GuidesPageRaw from "@/views/practice/GuidesPage"
import HealthWaiverPageRaw from "@/views/reviews/HealthWaiverPage"
import InvitationRoundsPageRaw from "@/views/skilled/InvitationRoundsPage"
import LabourAgreementPageRaw from "@/views/employer-sponsored/LabourAgreementPage"
import LabourMarketTestingPageRaw from "@/views/employer-sponsored/LabourMarketTestingPage"
import MedicalTreatment602PageRaw from "@/views/visitor-other/MedicalTreatment602Page"
import MinisterialInterventionPageRaw from "@/views/reviews/MinisterialInterventionPage"
import NationalInnovationVisaPageRaw from "@/views/skilled/NationalInnovationVisaPage"
import NaturalJusticeS57PageRaw from "@/views/reviews/NaturalJusticeS57Page"
import NewsPageRaw from "@/views/practice/NewsPage"
import NoFurtherStay8503PageRaw from "@/views/reviews/NoFurtherStay8503Page"
import NzFamilyRelationship461PageRaw from "@/views/partner-family/NzFamilyRelationship461Page"
import OccupationCaveatsPageRaw from "@/views/employer-sponsored/OccupationCaveatsPage"
import OccupationsListPage186Raw from "@/views/employer-sponsored/OccupationsListPage186"
import OrphanRelativeVisaPageRaw from "@/views/partner-family/OrphanRelativeVisaPage"
import ParentVisa103PageRaw from "@/views/partner-family/ParentVisa103Page"
import ParentVisaPageRaw from "@/views/visitor-other/ParentVisaPage"
import ParentVisasHubPageRaw from "@/views/partner-family/ParentVisasHubPage"
import PartnerFamilyHubPageRaw from "@/views/partner-family/PartnerFamilyHubPage"
import PartnerVisa309PageRaw from "@/views/partner-family/PartnerVisa309Page"
import PartnerVisa820PageRaw from "@/views/partner-family/PartnerVisa820Page"
import PartnerVisaEvidencePageRaw from "@/views/partner-family/PartnerVisaEvidencePage"
import Pathway482ToPRPageRaw from "@/views/employer-sponsored/Pathway482ToPRPage"
import PermanentResidenceSkillsRegionalPageRaw from "@/views/employer-sponsored/PermanentResidenceSkillsRegionalPage"
import Pic4020PageRaw from "@/views/reviews/Pic4020Page"
import PointsTestPageRaw from "@/views/skilled/PointsTestPage"
import PreAssessmentPageRaw from "@/views/PreAssessmentPage"
import ProspectiveMarriage300PageRaw from "@/views/partner-family/ProspectiveMarriage300Page"
import ProtectionVisa866PageRaw from "@/views/visitor-other/ProtectionVisa866Page"
import ReEntryBansPageRaw from "@/views/reviews/ReEntryBansPage"
import RegionalAreasPageRaw from "@/views/skilled/RegionalAreasPage"
import RegionalEmployer494PageRaw from "@/views/employer-sponsored/RegionalEmployer494Page"
import RemainingRelativeVisaPageRaw from "@/views/partner-family/RemainingRelativeVisaPage"
import ResidentReturnVisaPageRaw from "@/views/visitor-other/ResidentReturnVisaPage"
import ResourcesPageRaw from "@/views/practice/ResourcesPage"
import ReviewsPageRaw from "@/views/practice/ReviewsPage"
import Schedule3PageRaw from "@/views/reviews/Schedule3Page"
import Section48BarPageRaw from "@/views/reviews/Section48BarPage"
import ShortStaySpecialist400PageRaw from "@/views/employer-sponsored/ShortStaySpecialist400Page"
import SkilledIndependent189PageRaw from "@/views/skilled/SkilledIndependent189Page"
import SkilledMigrationHubPageRaw from "@/views/skilled/SkilledMigrationHubPage"
import SkilledNominated190PageRaw from "@/views/skilled/SkilledNominated190Page"
import SkilledRegional887PageRaw from "@/views/skilled/SkilledRegional887Page"
import SkilledWorkRegional491PageRaw from "@/views/skilled/SkilledWorkRegional491Page"
import SkillingAustraliansFundPageRaw from "@/views/employer-sponsored/SkillingAustraliansFundPage"
import SkillRequirements186PageRaw from "@/views/employer-sponsored/SkillRequirements186Page"
import SkillsAssessmentPageRaw from "@/views/skilled/SkillsAssessmentPage"
import SkillSelectEOIPageRaw from "@/views/skilled/SkillSelectEOIPage"
import SkillsInDemand482PageRaw from "@/views/employer-sponsored/SkillsInDemand482Page"
import SpecialCategory444PageRaw from "@/views/visitor-other/SpecialCategory444Page"
import SpecialistSkillsStreamPageRaw from "@/views/employer-sponsored/SpecialistSkillsStreamPage"
import SponsoredParent870PageRaw from "@/views/partner-family/SponsoredParent870Page"
import StandardBusinessSponsorshipPageRaw from "@/views/employer-sponsored/StandardBusinessSponsorshipPage"
import StateNominationPageRaw from "@/views/skilled/StateNominationPage"
import StudentFinancialCapacityPageRaw from "@/views/student/StudentFinancialCapacityPage"
import StudentGuardian590PageRaw from "@/views/student/StudentGuardian590Page"
import StudentToPRPageRaw from "@/views/student/StudentToPRPage"
import StudentVisa500PageRaw from "@/views/student/StudentVisa500Page"
import StudentVisasHubPageRaw from "@/views/student/StudentVisasHubPage"
import TemporaryActivity408PageRaw from "@/views/employer-sponsored/TemporaryActivity408Page"
import TemporaryGraduate485PageRaw from "@/views/skilled/TemporaryGraduate485Page"
import TemporaryWork403PageRaw from "@/views/employer-sponsored/TemporaryWork403Page"
import ToolsPageRaw from "@/views/practice/ToolsPage"
import TrainingVisa407PageRaw from "@/views/employer-sponsored/TrainingVisa407Page"
import Visa482ConditionsPageRaw from "@/views/employer-sponsored/Visa482ConditionsPage"
import VisaCancellationPageRaw from "@/views/reviews/VisaCancellationPage"
import VisaRefusalReviewHubPageRaw from "@/views/reviews/VisaRefusalReviewHubPage"
import VisitorOtherHubPageRaw from "@/views/visitor-other/VisitorOtherHubPage"
import VisitorVisa600PageRaw from "@/views/visitor-other/VisitorVisa600Page"
import VisitorVisaPageRaw from "@/views/visitor-other/VisitorVisaPage"
import VisitorVisasHubPageRaw from "@/views/visitor-other/VisitorVisasHubPage"
import WorkAndHoliday462PageRaw from "@/views/visitor-other/WorkAndHoliday462Page"
import WorkingHoliday417PageRaw from "@/views/visitor-other/WorkingHoliday417Page"

const ARTReviewPage = withNavigate(ARTReviewPageRaw as never)
const AboutPage = withNavigate(AboutPageRaw as never)
const AdoptionVisa102Page = withNavigate(AdoptionVisa102PageRaw as never)
const AgedDependentRelativePage = withNavigate(AgedDependentRelativePageRaw as never)
const AgedParent804Page = withNavigate(AgedParent804PageRaw as never)
const AssuranceOfSupportPage = withNavigate(AssuranceOfSupportPageRaw as never)
const AustralianCitizenshipPage = withNavigate(AustralianCitizenshipPageRaw as never)
const BalanceOfFamilyTestPage = withNavigate(BalanceOfFamilyTestPageRaw as never)
const BlogPage = withNavigate(BlogPageRaw as never)
const BookConsultationPage = withNavigate(BookConsultationPageRaw as never)
const BookPage = withNavigate(BookPageRaw as never)
const BridgingVisasPage = withNavigate(BridgingVisasPageRaw as never)
const CarerVisaPage = withNavigate(CarerVisaPageRaw as never)
const ChangeOfEmployerPage = withNavigate(ChangeOfEmployerPageRaw as never)
const ChecklistsPage = withNavigate(ChecklistsPageRaw as never)
const ChildVisa101Page = withNavigate(ChildVisa101PageRaw as never)
const ChildVisa802Page = withNavigate(ChildVisa802PageRaw as never)
const ContactPage = withNavigate(ContactPageRaw as never)
const ContributoryAgedParent864Page = withNavigate(ContributoryAgedParent864PageRaw as never)
const ContributoryAgedParent884Page = withNavigate(ContributoryAgedParent884PageRaw as never)
const ContributoryParent143Page = withNavigate(ContributoryParent143PageRaw as never)
const ContributoryParent173Page = withNavigate(ContributoryParent173PageRaw as never)
const CoreSkillsOccupationListPage = withNavigate(CoreSkillsOccupationListPageRaw as never)
const CoreSkillsStreamPage = withNavigate(CoreSkillsStreamPageRaw as never)
const CoursesPRProspectsPage = withNavigate(CoursesPRProspectsPageRaw as never)
const DAMAPage = withNavigate(DAMAPageRaw as never)
const DependentChild445Page = withNavigate(DependentChild445PageRaw as never)
const EmployerNomination186Page = withNavigate(EmployerNomination186PageRaw as never)
const EmployerObligationsPage = withNavigate(EmployerObligationsPageRaw as never)
const EmployerSponsorshipPage = withNavigate(EmployerSponsorshipPageRaw as never)
const EnglishRequirementsPage = withNavigate(EnglishRequirementsPageRaw as never)
const Eta601Page = withNavigate(Eta601PageRaw as never)
const Evisitor651Page = withNavigate(Evisitor651PageRaw as never)
const GenuinePositionPage = withNavigate(GenuinePositionPageRaw as never)
const GenuineStudentRequirementPage = withNavigate(GenuineStudentRequirementPageRaw as never)
const GuidesPage = withNavigate(GuidesPageRaw as never)
const HealthWaiverPage = withNavigate(HealthWaiverPageRaw as never)
const InvitationRoundsPage = withNavigate(InvitationRoundsPageRaw as never)
const LabourAgreementPage = withNavigate(LabourAgreementPageRaw as never)
const LabourMarketTestingPage = withNavigate(LabourMarketTestingPageRaw as never)
const MedicalTreatment602Page = withNavigate(MedicalTreatment602PageRaw as never)
const MinisterialInterventionPage = withNavigate(MinisterialInterventionPageRaw as never)
const NationalInnovationVisaPage = withNavigate(NationalInnovationVisaPageRaw as never)
const NaturalJusticeS57Page = withNavigate(NaturalJusticeS57PageRaw as never)
const NewsPage = withNavigate(NewsPageRaw as never)
const NoFurtherStay8503Page = withNavigate(NoFurtherStay8503PageRaw as never)
const NzFamilyRelationship461Page = withNavigate(NzFamilyRelationship461PageRaw as never)
const OccupationCaveatsPage = withNavigate(OccupationCaveatsPageRaw as never)
const OccupationsListPage186 = withNavigate(OccupationsListPage186Raw as never)
const OrphanRelativeVisaPage = withNavigate(OrphanRelativeVisaPageRaw as never)
const ParentVisa103Page = withNavigate(ParentVisa103PageRaw as never)
const ParentVisaPage = withNavigate(ParentVisaPageRaw as never)
const ParentVisasHubPage = withNavigate(ParentVisasHubPageRaw as never)
const PartnerFamilyHubPage = withNavigate(PartnerFamilyHubPageRaw as never)
const PartnerVisa309Page = withNavigate(PartnerVisa309PageRaw as never)
const PartnerVisa820Page = withNavigate(PartnerVisa820PageRaw as never)
const PartnerVisaEvidencePage = withNavigate(PartnerVisaEvidencePageRaw as never)
const Pathway482ToPRPage = withNavigate(Pathway482ToPRPageRaw as never)
const PermanentResidenceSkillsRegionalPage = withNavigate(PermanentResidenceSkillsRegionalPageRaw as never)
const Pic4020Page = withNavigate(Pic4020PageRaw as never)
const PointsTestPage = withNavigate(PointsTestPageRaw as never)
const PreAssessmentPage = withNavigate(PreAssessmentPageRaw as never)
const ProspectiveMarriage300Page = withNavigate(ProspectiveMarriage300PageRaw as never)
const ProtectionVisa866Page = withNavigate(ProtectionVisa866PageRaw as never)
const ReEntryBansPage = withNavigate(ReEntryBansPageRaw as never)
const RegionalAreasPage = withNavigate(RegionalAreasPageRaw as never)
const RegionalEmployer494Page = withNavigate(RegionalEmployer494PageRaw as never)
const RemainingRelativeVisaPage = withNavigate(RemainingRelativeVisaPageRaw as never)
const ResidentReturnVisaPage = withNavigate(ResidentReturnVisaPageRaw as never)
const ResourcesPage = withNavigate(ResourcesPageRaw as never)
const ReviewsPage = withNavigate(ReviewsPageRaw as never)
const Schedule3Page = withNavigate(Schedule3PageRaw as never)
const Section48BarPage = withNavigate(Section48BarPageRaw as never)
const ShortStaySpecialist400Page = withNavigate(ShortStaySpecialist400PageRaw as never)
const SkillRequirements186Page = withNavigate(SkillRequirements186PageRaw as never)
const SkillSelectEOIPage = withNavigate(SkillSelectEOIPageRaw as never)
const SkilledIndependent189Page = withNavigate(SkilledIndependent189PageRaw as never)
const SkilledMigrationHubPage = withNavigate(SkilledMigrationHubPageRaw as never)
const SkilledNominated190Page = withNavigate(SkilledNominated190PageRaw as never)
const SkilledRegional887Page = withNavigate(SkilledRegional887PageRaw as never)
const SkilledWorkRegional491Page = withNavigate(SkilledWorkRegional491PageRaw as never)
const SkillingAustraliansFundPage = withNavigate(SkillingAustraliansFundPageRaw as never)
const SkillsAssessmentPage = withNavigate(SkillsAssessmentPageRaw as never)
const SkillsInDemand482Page = withNavigate(SkillsInDemand482PageRaw as never)
const SpecialCategory444Page = withNavigate(SpecialCategory444PageRaw as never)
const SpecialistSkillsStreamPage = withNavigate(SpecialistSkillsStreamPageRaw as never)
const SponsoredParent870Page = withNavigate(SponsoredParent870PageRaw as never)
const StandardBusinessSponsorshipPage = withNavigate(StandardBusinessSponsorshipPageRaw as never)
const StateNominationPage = withNavigate(StateNominationPageRaw as never)
const StudentFinancialCapacityPage = withNavigate(StudentFinancialCapacityPageRaw as never)
const StudentGuardian590Page = withNavigate(StudentGuardian590PageRaw as never)
const StudentToPRPage = withNavigate(StudentToPRPageRaw as never)
const StudentVisa500Page = withNavigate(StudentVisa500PageRaw as never)
const StudentVisasHubPage = withNavigate(StudentVisasHubPageRaw as never)
const TemporaryActivity408Page = withNavigate(TemporaryActivity408PageRaw as never)
const TemporaryGraduate485Page = withNavigate(TemporaryGraduate485PageRaw as never)
const TemporaryWork403Page = withNavigate(TemporaryWork403PageRaw as never)
const ToolsPage = withNavigate(ToolsPageRaw as never)
const TrainingVisa407Page = withNavigate(TrainingVisa407PageRaw as never)
const Visa482ConditionsPage = withNavigate(Visa482ConditionsPageRaw as never)
const VisaCancellationPage = withNavigate(VisaCancellationPageRaw as never)
const VisaRefusalReviewHubPage = withNavigate(VisaRefusalReviewHubPageRaw as never)
const VisitorOtherHubPage = withNavigate(VisitorOtherHubPageRaw as never)
const VisitorVisa600Page = withNavigate(VisitorVisa600PageRaw as never)
const VisitorVisaPage = withNavigate(VisitorVisaPageRaw as never)
const VisitorVisasHubPage = withNavigate(VisitorVisasHubPageRaw as never)
const WorkAndHoliday462Page = withNavigate(WorkAndHoliday462PageRaw as never)
const WorkingHoliday417Page = withNavigate(WorkingHoliday417PageRaw as never)
const Home = withNavigate(HomePage as never)
const Privacy = withNavigate(function Privacy(p: { navigate: (page: string) => void }) { return <LegalPage kind="privacy" navigate={p.navigate} /> } as never)
const Terms = withNavigate(function Terms(p: { navigate: (page: string) => void }) { return <LegalPage kind="terms" navigate={p.navigate} /> } as never)
const Accessibility = withNavigate(function Accessibility(p: { navigate: (page: string) => void }) { return <LegalPage kind="accessibility" navigate={p.navigate} /> } as never)

export type AppPageComponent = ComponentType

export const PAGE_REGISTRY: Record<string, AppPageComponent> = {
  "": Home,
  "186-occupations-list": OccupationsListPage186,
  "186-skill-requirements": SkillRequirements186Page,
  "191-visa": PermanentResidenceSkillsRegionalPage,
  "482-core-skills-stream": CoreSkillsStreamPage,
  "482-specialist-skills-stream": SpecialistSkillsStreamPage,
  "482-to-pr-pathway": Pathway482ToPRPage,
  "494-visa": RegionalEmployer494Page,
  "about": AboutPage,
  "accessibility": Accessibility,
  "adoption-visa-102": AdoptionVisa102Page,
  "aged-dependent-relative": AgedDependentRelativePage,
  "aged-parent-804": AgedParent804Page,
  "art-review": ARTReviewPage,
  "assurance-of-support": AssuranceOfSupportPage,
  "australian-citizenship": AustralianCitizenshipPage,
  "balance-of-family-test": BalanceOfFamilyTestPage,
  "blog": BlogPage,
  "book": BookPage,
  "book-consultation": BookConsultationPage,
  "bridging-visas": BridgingVisasPage,
  "carer-visa": CarerVisaPage,
  "change-of-employer": ChangeOfEmployerPage,
  "checklists": ChecklistsPage,
  "child-visa-101": ChildVisa101Page,
  "child-visa-802": ChildVisa802Page,
  "contact": ContactPage,
  "contributory-aged-parent-864": ContributoryAgedParent864Page,
  "contributory-aged-parent-884": ContributoryAgedParent884Page,
  "contributory-parent-143": ContributoryParent143Page,
  "contributory-parent-173": ContributoryParent173Page,
  "core-skills-occupation-list": CoreSkillsOccupationListPage,
  "courses-pr-prospects": CoursesPRProspectsPage,
  "dama": DAMAPage,
  "dependent-child-445": DependentChild445Page,
  "employer-nomination-scheme": EmployerNomination186Page,
  "employer-sponsored-visas": EmployerSponsorshipPage,
  "english-requirements": EnglishRequirementsPage,
  "eta-601": Eta601Page,
  "evisitor-651": Evisitor651Page,
  "genuine-position-test": GenuinePositionPage,
  "genuine-student-requirement": GenuineStudentRequirementPage,
  "guides": GuidesPage,
  "health-waiver": HealthWaiverPage,
  "invitation-rounds": InvitationRoundsPage,
  "labour-agreements": LabourAgreementPage,
  "labour-market-testing": LabourMarketTestingPage,
  "medical-treatment-602": MedicalTreatment602Page,
  "ministerial-intervention": MinisterialInterventionPage,
  "national-innovation-visa": NationalInnovationVisaPage,
  "natural-justice-s57": NaturalJusticeS57Page,
  "news": NewsPage,
  "no-further-stay-8503": NoFurtherStay8503Page,
  "nz-family-relationship-461": NzFamilyRelationship461Page,
  "occupation-caveats": OccupationCaveatsPage,
  "orphan-relative-visa": OrphanRelativeVisaPage,
  "parent-visa": ParentVisaPage,
  "parent-visa-103": ParentVisa103Page,
  "parent-visas": ParentVisasHubPage,
  "partner-family-visas": PartnerFamilyHubPage,
  "partner-visa-309-100": PartnerVisa309Page,
  "partner-visa-820-801": PartnerVisa820Page,
  "partner-visa-evidence": PartnerVisaEvidencePage,
  "pic-4020": Pic4020Page,
  "points-test": PointsTestPage,
  "pre-assessment": PreAssessmentPage,
  "privacy": Privacy,
  "prospective-marriage-300": ProspectiveMarriage300Page,
  "protection-visa-866": ProtectionVisa866Page,
  "re-entry-bans": ReEntryBansPage,
  "regional-areas": RegionalAreasPage,
  "remaining-relative-visa": RemainingRelativeVisaPage,
  "resident-return-visa": ResidentReturnVisaPage,
  "resources": ResourcesPage,
  "reviews": ReviewsPage,
  "saf-levy": SkillingAustraliansFundPage,
  "schedule-3": Schedule3Page,
  "section-48-bar": Section48BarPage,
  "short-stay-specialist-400": ShortStaySpecialist400Page,
  "skilled-independent-189": SkilledIndependent189Page,
  "skilled-migration": SkilledMigrationHubPage,
  "skilled-nominated-190": SkilledNominated190Page,
  "skilled-regional-887": SkilledRegional887Page,
  "skilled-work-regional-491": SkilledWorkRegional491Page,
  "skills-assessment": SkillsAssessmentPage,
  "skills-in-demand-visa": SkillsInDemand482Page,
  "skillselect-eoi": SkillSelectEOIPage,
  "special-category-444": SpecialCategory444Page,
  "sponsored-parent-870": SponsoredParent870Page,
  "sponsorship-obligations": EmployerObligationsPage,
  "standard-business-sponsorship": StandardBusinessSponsorshipPage,
  "state-nomination": StateNominationPage,
  "student-financial-capacity": StudentFinancialCapacityPage,
  "student-guardian-590": StudentGuardian590Page,
  "student-to-pr-pathway": StudentToPRPage,
  "student-visa-500": StudentVisa500Page,
  "student-visas": StudentVisasHubPage,
  "temporary-activity-408": TemporaryActivity408Page,
  "temporary-graduate-485": TemporaryGraduate485Page,
  "temporary-work-403": TemporaryWork403Page,
  "terms": Terms,
  "tools": ToolsPage,
  "training-visa-407": TrainingVisa407Page,
  "visa-cancellation": VisaCancellationPage,
  "visa-conditions-482": Visa482ConditionsPage,
  "visa-refusal-review": VisaRefusalReviewHubPage,
  "visitor-hub": VisitorOtherHubPage,
  "visitor-visa": VisitorVisaPage,
  "visitor-visa-600": VisitorVisa600Page,
  "visitor-visas": VisitorVisasHubPage,
  "work-and-holiday-462": WorkAndHoliday462Page,
  "working-holiday-417": WorkingHoliday417Page,
}

export function getRegistryPage(slugPath: string): AppPageComponent | null {
  const key = slugPath.replace(/^\/+|\/+$/g, "")
  return PAGE_REGISTRY[key] ?? null
}

export const REGISTRY_PATHS = Object.keys(PAGE_REGISTRY).filter(Boolean)
